number = []
n1=int(input("enter the number"))
number.append(n1)
n2=int(input("enter the number"))
number.append(n2)
n3=int(input("enter the number"))
number.append(n3)
n4=int(input("enter the number"))
number.append(n4)
n5=int(input("enter the number"))
number.append(n5)
n6=int(input("enter the number"))
number.append(n6)
n7=int(input("enter the number"))
number.append(n7)
n8=int(input("enter the number"))
number.append(n8)
number.sort()
print(number)